services:
  postgres:
    image: postgres:15-alpine
    container_name: todoapp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: todoapp_db
      POSTGRES_USER: todoapp
      POSTGRES_PASSWORD: todoapp123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todoapp-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: todoapp-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@todoapp.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - todoapp-network

volumes:
  postgres_data:

networks:
  todoapp-network:
    driver: bridge
